name: Deploy Python App

on:
  push:
    branches:
      - main  # Αντικαταστήστε το "main" με το όνομα της κύριας branch σας

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass  # Εγκατάσταση sshpass

      - name: Copy files to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}  # Ρύθμισε το SERVER_IP στα GitHub secrets
          USERNAME: ${{ secrets.USERNAME }}     # Ρύθμισε το USERNAME στα GitHub secrets
          PASSWORD: ${{ secrets.PASSWORD }}     # Ρύθμισε το PASSWORD στα GitHub secrets
        run: |
          echo "Using SERVER_IP: $SERVER_IP"
          echo "Using USERNAME: $USERNAME"
          # Δημιουργία φακέλου στον server
          sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP "mkdir -p /var/repo"
          # Αντιγραφή όλων των αρχείων εκτός από αυτά που δεν χρειάζονται (π.χ. .git, .github)
          sshpass -p $PASSWORD rsync -av --exclude='.git/' --exclude='.github/' . $USERNAME@$SERVER_IP:/var/repo

      - name: Install dependencies on server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP "sudo apt-get update && sudo apt-get install -y python3-pip && pip3 install --upgrade pip && pip3 install -r /var/repo/requirements.txt"

      - name: Restart the application
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP "sudo systemctl restart myapp"
