name: Deploy Python App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Αλλάξτε την έκδοση Python ανάλογα

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build the application
        run: python setup.py sdist bdist_wheel

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /var/repo
            cd /var/repo
            rm -rf *
            scp -r dist/* user@server:/var/repo
            # Εκτελέστε εντολές για την εκκίνηση της εφαρμογής
            sudo systemctl restart your_service  # Αν χρησιμοποιείτε systemd
