name: Deploy Python App

on:
  push:
    branches:
      - main  # Αντικατάστησε το "main" με το όνομα της κύριας branch σου

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass  # Εγκατάσταση sshpass

      - name: Copy files to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}  # Ρύθμισε το SERVER_IP στα GitHub secrets
          USERNAME: ${{ secrets.USERNAME }}     # Ρύθμισε το USERNAME στα GitHub secrets
          PASSWORD: ${{ secrets.PASSWORD }}     # Ρύθμισε το PASSWORD στα GitHub secrets
        run: |
          echo "Using SERVER_IP: $SERVER_IP"
          echo "Using USERNAME: $USERNAME"
          # Δημιουργία φακέλου στον server
          sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP "mkdir -p /var/repo"
          # Αντιγραφή όλων των αρχείων εκτός από αυτά που δεν χρειάζονται (π.χ. .git, .github)
          sshpass -p $PASSWORD rsync -av --exclude='.git/' --exclude='.github/' . $USERNAME@$SERVER_IP:/var/repo

      - name: Set up Python on server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
    
