name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to server
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << 'EOF'
          # Εγκατάσταση Docker και Docker Compose αν δεν είναι ήδη εγκατεστημένα
          if ! command -v docker &> /dev/null; then
            echo "Docker not found, installing..."
            sudo apt-get update
            sudo apt-get install -y docker.io
          fi
          
          if ! command -v docker-compose &> /dev/null; then
            echo "Docker Compose not found, installing..."
            sudo apt-get install -y docker-compose
          fi

          # Έλεγχος αν υπάρχει ο φάκελος και διαχείριση
          if [ -d $REPO_PATH ]; then
            echo "'$REPO_PATH' exists."
            if [ -d "$REPO_PATH/.git" ]; then
              echo "Updating existing repository..."
              cd $REPO_PATH
              git pull || { echo 'Git pull failed'; exit 1; }
            else
              echo "Error: '$REPO_PATH' exists but is not a git repository. Deleting it."
              rm -rf $REPO_PATH
              echo "Cloning repository..."
              git clone https://github.com/panagiotislivanis/coupons.git $REPO_PATH || { echo 'Cloning failed'; exit 1; }
            fi
          else
            echo "Cloning repository..."
            git clone https://github.com/panagiotislivanis/coupons.git $REPO_PATH || { echo 'Cloning failed'; exit 1; }
          fi
          
          cd $REPO_PATH
          echo 'Current directory: ' $(pwd)
          ls -l

          # Δημιουργία του φακέλου back αν δεν υπάρχει
          if [ ! -d "back" ]; then
            echo "Creating back directory..."
            mkdir back
          fi

          cd back
          echo 'Current directory after changing: ' $(pwd)
          ls -l
          
          # Εκτέλεση Docker Compose
          if [ -f "docker-compose.yml" ]; then
            /snap/bin/docker-compose up --build -d
          else
            echo "Error: 'docker-compose.yml' file does not exist in 'back' directory."
            exit 1
          fi
          EOF
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          REPO_PATH: /var/repo/coupons
